### ISSUE TITLE
[230905 오늘의 문제] - 숫자 할리갈리 게임

### ISSUE THREAD

**Issue by Jo-wonbin** [1day1AlgoGoGo/Algorithm#10]
# [230905 오늘의 문제] - 숫자 할리갈리 게임
## 백준_시뮬레이션_숫자 할리갈리 게임 [https://www.acmicpc.net/problem/20923](https://www.acmicpc.net/problem/20923)

**Comment by simjaeseo** [comment]
와 방금 딱 문제 찾아왔는데 올라왔네

**Comment by Jo-wonbin** [comment]
ㅋㅋㅋㅋ이슈엔 안 올라가 있지만 230830 문제 마인크래프트도 풀어보세용

**Comment by Jo-wonbin** [comment]
230830 - [시뮬레이션]_백준_마인크래프트[https://www.acmicpc.net/problem/18111](https://www.acmicpc.net/problem/18111)

**Comment by simjaeseo** [comment]
> 230830 - [시뮬레이션]_백준_마인크래프트https://www.acmicpc.net/problem/18111

네형
