### ISSUE TITLE
앞으로 Merge하기 위해서는 팀원 2명의 Approve를 받아야합니다.

### ISSUE THREAD

**Issue by simjaeseo** [1day1AlgoGoGo/Algorithm#31]
## 참고 링크 - [https://mine-it-record.tistory.com/692](https://mine-it-record.tistory.com/692)

PR에 리뷰어랑 어사이니 추가만 하면 자동으로 세팅되는건줄 알았는데 그게 아니었네여
여기에 세팅 과정이랑 approve 하는 방법 다 나와있으니 참고해주세여~~

**Comment by jg6735** [comment]
좋은 룰 같아요. 정보 공유 굿

**Comment by Jo-wonbin** [comment]
네넹
