### ISSUE TITLE
Approve 후 Merge하는 사람

### ISSUE THREAD

**Issue by simjaeseo** [1day1AlgoGoGo/Algorithm#38]
원래 원빈이랑 둘이했을때는 코드리뷰 남기고 바로 그 사람이 Merge 눌렀잖아?

지금 Approve도 생겼으니, 두 사람이 코드리뷰 남기고 Approve 둘다 하면, 코드리뷰 확인하고 PR 올린 사람이 Merge 하는걸로 하는거어때? (PR올린사람이 Merge 눌러야 리뷰 남긴거 확인할 수 있으니)

**Comment by Jo-wonbin** [comment]
ㅇㅋ
